### ISSUE TITLE
Suggestions: Change title color

### ISSUE THREAD

**Issue by art-seva1** [art-seva/github-crash-course#1]
I think it looks better if the main title is a bit more orange

```css
h1 {
  color: #fea82e;
}
```
